function feature_map_norm = feature_norm(x)
feature_map_norm = bsxfun(@times, x, ...
            sqrt((size(x,1)*size(x,2))^1* size(x,3)^1 ./ ...
            (sum(reshape(x, [], 1, 1, size(x,4)).^2, 1) + eps)));